pciem_userspace: properly check per-CPU errors
In newer kernels, compiling the kernel-mode driver gives the following
error:

    framework/pciem_userspace.c: In function ‘pciem_ioctl_set_watchpoint’:
    framework/pciem_userspace.c:976:40: error: passing argument 1 of ‘IS_ERR’ from pointer to non-enclosed address space
      976 |     if (IS_ERR(us->watchpoints[wp_slot].perf_bp))
          |                ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~

This is because the pointer returned from register_wide_hw_breakpoint()
is of type `struct perf_event * __percpu *`. In newer kernels, the error
from this pointer can be checked with IS_ERR_PCPU(), so use it. For
older kernels, add the equivalent define.